### ISSUE TITLE
[Might just be me] XML -> BLO won't find my .bti textures.

### ISSUE THREAD

**Issue by MelonSpeedruns** [arookas/blojob#1]
A solution might be to make so that XML -> BLO doesn't care about where the textures are, and just write their names in the new .blo .

**Comment by arookas** [comment]
Unfortunately, while that is doable for textures and palette resources, it cannot be done for font resources as it stands, as that needs to load the BFN to get the encoding use to write the text buffer. I might be able to add an encoding attribute to the text element in the XML so the font loading isn't necessary but that would require some refactoring. I'll look into it.
